### ISSUE TITLE
Annelid hangs on restart

### ISSUE THREAD

**Issue by tandrewnichols** [dagit/annelid#4] opened 2023-03-14 01:22 UTC
I've mentioned this to you directly, but so you have some record of it, annelid sometimes hangs on restart. I _think_ it happens when either qusb2snes isn't running _or_ annelid isn't connected to it. When everything is set up right, it seems to work fine. It had just started happening to me again, and then I noticed qusb2snes wasn't running (I assume it must've crashed cause I did start it). Once I started it up again, restarting in annelid worked fine.

**Comment by dagit** [comment] 2023-03-14 07:56
Thanks for the reminder. I think I know what the problem might be. I think it's just an issue with the restart logic. I use separate threads for talking to qusb2snes vs the ui. I think maybe in the case where I never connect to qusb2snes that thread doesn't make it into the right state to be able to restart.

**Comment by dagit** [comment] 2023-03-20 00:40
I just tested this on linux and I can't reproduce it. I'll test on macOS as soon as I can, but I think it not happening on linux is probably how it became on issue.

**Comment by dagit** [comment] 2023-06-14 04:53
I think I fixed the issue. I'm going to close this. If you try a recent release and still have the issue, please let me know.

**Closed by dagit** 2023-06-14 04:53 UTC
